//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var answer=0; 
var limit= 4000000;
for (i= 1; i < limit;){
    for(j = 1; i < limit;){
        i+= j;
        j+= i; 
        if (i%2=== 0 && i< limit){
        answer += i;
        }
        else if (j%2 === 0 && j<limit){
            answer += j;
        }
       
    }
    console.log(answer); 
}